import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./AgentOrchestrationFlow.tsx",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-container": "#ffca3f",
        "surface-container-highest": "#f5db90",
        "on-secondary-container": "#5b4400",
        "secondary-fixed": "#ffca3f",
        "secondary-dim": "#654c00",
        "outline-variant": "#bfac76",
        "on-primary-fixed": "#4a4400",
        tertiary: "#5f5f00",
        "on-tertiary": "#fbf95c",
        "error-container": "#f95630",
        "on-primary-container": "#5e5600",
        "inverse-surface": "#130d00",
        "surface-container-low": "#fff0ca",
        "surface-dim": "#edd283",
        "tertiary-container": "#f6f557",
        "secondary-fixed-dim": "#f0bd30",
        outline: "#867645",
        "surface-tint": "#655d00",
        "on-secondary": "#fff1d9",
        "surface-bright": "#fff5e4",
        "on-tertiary-container": "#5c5b00",
        "surface-container-lowest": "#ffffff",
        "on-background": "#392d04",
        "tertiary-fixed": "#f6f557",
        error: "#b02500",
        "on-primary": "#fff5a9",
        "inverse-on-surface": "#ae9c67",
        "on-error-container": "#520c00",
        "surface-container-high": "#fae199",
        "surface-variant": "#f5db90",
        "on-surface": "#392d04",
        "on-error": "#ffefec",
        "primary-fixed": "#faeb61",
        "surface-container": "#ffe7a3",
        "inverse-primary": "#faeb61",
        "tertiary-fixed-dim": "#e7e64a",
        secondary: "#735700",
        "on-secondary-fixed": "#433200",
        surface: "#fff5e4",
        "primary-fixed-dim": "#ecdd54",
        "primary-dim": "#585100",
        "on-surface-variant": "#695a2d",
        "error-dim": "#b92902",
        "on-tertiary-fixed-variant": "#666600",
        "on-tertiary-fixed": "#494900",
        "on-secondary-fixed-variant": "#664d00",
        "primary-container": "#faeb61",
        primary: "#655d00",
        "on-primary-fixed-variant": "#696000",
        background: "#fff5e4",
        "tertiary-dim": "#535200",
      },
      fontFamily: {
        headline: ["Public Sans", "sans-serif"],
        body: ["Public Sans", "sans-serif"],
        label: ["Noto Serif", "serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};

export default config;
